### PR TITLE
Frontend refactor

### PR DESCRIPTION
**Pull request by mattearnshaw**

### CODE REVIEW

**Comment by mattearnshaw** [comment]
(for an index of improvement, compare the number of <script> tags rendered into a typical page...)

**Comment by tarelli** [comment]
@mattearnshaw Minor cosmetic. Different colours between buttons and logo. Also two different types of blue (button and question mark should be the same).
screen shot 2017-04-07 at 09 28 17

**Comment by tarelli** [comment]
@mattearnshaw any plans to update FontAwesome?

**Comment by mattearnshaw** [comment]
@tarelli hadn't considered it, not a priority but might try if I'm at a loose end

**Comment by tarelli** [comment]
@mattearnshaw is this difference intended?
screen shot 2017-04-12 at 11 44 18

**Comment by tarelli** [comment]
screen shot 2017-04-12 at 12 20 49

**Comment by tarelli** [comment]
@pgleeson @mattearnshaw I'd update this to [Redmine 3.3.3](https://github.com/redmine/redmine/releases/tag/3.3.3) I tried to look at this locally to see what's the entity of the changes and, as expected, it's not trivial:

```
Auto-merging doc/CHANGELOG
CONFLICT (content): Merge conflict in doc/CHANGELOG
Auto-merging config/routes.rb
CONFLICT (content): Merge conflict in config/routes.rb
Removing config/preinitializer.rb
Auto-merging config/locales/tr.yml
Auto-merging config/locales/ru.yml
CONFLICT (content): Merge conflict in config/locales/ru.yml
Auto-merging config/locales/pl.yml
CONFLICT (content): Merge conflict in config/locales/pl.yml
Auto-merging config/locales/ko.yml
CONFLICT (content): Merge conflict in config/locales/ko.yml
Auto-merging config/locales/ja.yml
CONFLICT (content): Merge conflict in config/locales/ja.yml
Auto-merging config/locales/fr.yml
CONFLICT (content): Merge conflict in config/locales/fr.yml
Auto-merging config/locales/es.yml
CONFLICT (content): Merge conflict in config/locales/es.yml
Auto-merging config/locales/en.yml
Auto-merging config/locales/en-GB.yml
Auto-merging config/locales/cs.yml
CONFLICT (content): Merge conflict in config/locales/cs.yml
Auto-merging config/application.rb
Auto-merging app/views/wiki/show.html.erb
CONFLICT (content): Merge conflict in app/views/wiki/show.html.erb
Auto-merging app/views/wiki/index.html.erb
Auto-merging app/views/wiki/edit.html.erb
CONFLICT (content): Merge conflict in app/views/wiki/edit.html.erb
Auto-merging app/views/welcome/index.html.erb
CONFLICT (content): Merge conflict in app/views/welcome/index.html.erb
Auto-merging app/views/users/show.html.erb
CONFLICT (content): Merge conflict in app/views/users/show.html.erb
Auto-merging app/views/users/index.html.erb
Auto-merging app/views/users/edit.html.erb
CONFLICT (content): Merge conflict in app/views/users/edit.html.erb
Auto-merging app/views/users/_general.html.erb
Auto-merging app/views/search/index.html.erb
CONFLICT (content): Merge conflict in app/views/search/index.html.erb
Auto-merging app/views/repositories/show.html.erb
Auto-merging app/views/repositories/_revisions.html.erb
Auto-merging app/views/repositories/_dir_list_content.html.erb
CONFLICT (content): Merge conflict in app/views/repositories/_dir_list_content.html.erb
Auto-merging app/views/queries/_form.html.erb
Auto-merging app/views/queries/_filters.html.erb
CONFLICT (content): Merge conflict in app/views/queries/_filters.html.erb
Auto-merging app/views/queries/_columns.html.erb
Auto-merging app/views/projects/show.html.erb
CONFLICT (content): Merge conflict in app/views/projects/show.html.erb
Auto-merging app/views/projects/settings/_versions.html.erb
Auto-merging app/views/projects/settings/_repositories.html.erb
Auto-merging app/views/projects/settings/_members.html.erb
CONFLICT (content): Merge conflict in app/views/projects/settings/_members.html.erb
Auto-merging app/views/projects/settings/_issue_categories.html.erb
Auto-merging app/views/projects/settings/_boards.html.erb
CONFLICT (content): Merge conflict in app/views/projects/settings/_boards.html.erb
Removing app/views/projects/list_members.html.erb
Auto-merging app/views/projects/index.html.erb
CONFLICT (content): Merge conflict in app/views/projects/index.html.erb
Auto-merging app/views/projects/copy.html.erb
Auto-merging app/views/projects/_members_box.html.erb
CONFLICT (content): Merge conflict in app/views/projects/_members_box.html.erb
Auto-merging app/views/projects/_form.html.erb
CONFLICT (content): Merge conflict in app/views/projects/_form.html.erb
Auto-merging app/views/news/index.html.erb
Auto-merging app/views/my/password.html.erb
Auto-merging app/views/my/account.html.erb
CONFLICT (content): Merge conflict in app/views/my/account.html.erb
Auto-merging app/views/mailer/account_activated.html.erb
CONFLICT (content): Merge conflict in app/views/mailer/account_activated.html.erb
Auto-merging app/views/layouts/base.html.erb
CONFLICT (content): Merge conflict in app/views/layouts/base.html.erb
Auto-merging app/views/issues/show.html.erb
CONFLICT (content): Merge conflict in app/views/issues/show.html.erb
Auto-merging app/views/issues/new.html.erb
CONFLICT (content): Merge conflict in app/views/issues/new.html.erb
Auto-merging app/views/issues/index.html.erb
CONFLICT (content): Merge conflict in app/views/issues/index.html.erb
Auto-merging app/views/issues/_list.html.erb
CONFLICT (content): Merge conflict in app/views/issues/_list.html.erb
Auto-merging app/views/issues/_history.html.erb
CONFLICT (content): Merge conflict in app/views/issues/_history.html.erb
Auto-merging app/views/issues/_form.html.erb
CONFLICT (content): Merge conflict in app/views/issues/_form.html.erb
Auto-merging app/views/issues/_changesets.html.erb
CONFLICT (content): Merge conflict in app/views/issues/_changesets.html.erb
Auto-merging app/views/issues/_attributes.html.erb
CONFLICT (content): Merge conflict in app/views/issues/_attributes.html.erb
Auto-merging app/views/issues/_action_menu.html.erb
CONFLICT (content): Merge conflict in app/views/issues/_action_menu.html.erb
Auto-merging app/views/groups/show.html.erb
CONFLICT (content): Merge conflict in app/views/groups/show.html.erb
Auto-merging app/views/groups/_users.html.erb
CONFLICT (content): Merge conflict in app/views/groups/_users.html.erb
Auto-merging app/views/groups/_memberships.html.erb
CONFLICT (content): Merge conflict in app/views/groups/_memberships.html.erb
Auto-merging app/views/groups/_general.html.erb
Auto-merging app/views/groups/_form.html.erb
CONFLICT (content): Merge conflict in app/views/groups/_form.html.erb
Auto-merging app/views/files/index.html.erb
Auto-merging app/views/custom_fields/new.html.erb
CONFLICT (content): Merge conflict in app/views/custom_fields/new.html.erb
Auto-merging app/views/custom_fields/_form.html.erb
CONFLICT (content): Merge conflict in app/views/custom_fields/_form.html.erb
Auto-merging app/views/common/error.html.erb
CONFLICT (content): Merge conflict in app/views/common/error.html.erb
Auto-merging app/views/common/_tabs.html.erb
CONFLICT (content): Merge conflict in app/views/common/_tabs.html.erb
Auto-merging app/views/activities/index.html.erb
CONFLICT (content): Merge conflict in app/views/activities/index.html.erb
Auto-merging app/views/account/register.html.erb
CONFLICT (content): Merge conflict in app/views/account/register.html.erb
Auto-merging app/views/account/login.html.erb
CONFLICT (content): Merge conflict in app/views/account/login.html.erb
Auto-merging app/models/wiki_page.rb
Auto-merging app/models/wiki_content.rb
CONFLICT (content): Merge conflict in app/models/wiki_content.rb
Auto-merging app/models/user.rb
Auto-merging app/models/time_entry.rb
CONFLICT (content): Merge conflict in app/models/time_entry.rb
Auto-merging app/models/repository.rb
CONFLICT (content): Merge conflict in app/models/repository.rb
Auto-merging app/models/project.rb
CONFLICT (content): Merge conflict in app/models/project.rb
Auto-merging app/models/news.rb
CONFLICT (content): Merge conflict in app/models/news.rb
Auto-merging app/models/mailer.rb
Auto-merging app/models/issue_query.rb
Auto-merging app/models/issue.rb
Auto-merging app/models/custom_value.rb
Auto-merging app/models/custom_field_value.rb
Auto-merging app/models/custom_field.rb
CONFLICT (content): Merge conflict in app/models/custom_field.rb
Auto-merging app/helpers/wiki_helper.rb
CONFLICT (content): Merge conflict in app/helpers/wiki_helper.rb
Auto-merging app/helpers/watchers_helper.rb
CONFLICT (content): Merge conflict in app/helpers/watchers_helper.rb
Auto-merging app/helpers/users_helper.rb
CONFLICT (content): Merge conflict in app/helpers/users_helper.rb
Auto-merging app/helpers/search_helper.rb
Auto-merging app/helpers/queries_helper.rb
CONFLICT (content): Merge conflict in app/helpers/queries_helper.rb
Auto-merging app/helpers/projects_helper.rb
CONFLICT (content): Merge conflict in app/helpers/projects_helper.rb
Auto-merging app/helpers/issues_helper.rb
CONFLICT (content): Merge conflict in app/helpers/issues_helper.rb
Auto-merging app/helpers/custom_fields_helper.rb
Auto-merging app/helpers/application_helper.rb
CONFLICT (content): Merge conflict in app/helpers/application_helper.rb
Auto-merging app/controllers/wiki_controller.rb
Auto-merging app/controllers/welcome_controller.rb
CONFLICT (content): Merge conflict in app/controllers/welcome_controller.rb
Auto-merging app/controllers/watchers_controller.rb
Auto-merging app/controllers/users_controller.rb
CONFLICT (content): Merge conflict in app/controllers/users_controller.rb
Auto-merging app/controllers/search_controller.rb
CONFLICT (content): Merge conflict in app/controllers/search_controller.rb
Auto-merging app/controllers/repositories_controller.rb
Auto-merging app/controllers/projects_controller.rb
CONFLICT (content): Merge conflict in app/controllers/projects_controller.rb
Auto-merging app/controllers/messages_controller.rb
Auto-merging app/controllers/journals_controller.rb
Auto-merging app/controllers/issues_controller.rb
Auto-merging app/controllers/groups_controller.rb
Auto-merging app/controllers/application_controller.rb
CONFLICT (content): Merge conflict in app/controllers/application_controller.rb
Auto-merging app/controllers/account_controller.rb
Auto-merging Gemfile
CONFLICT (content): Merge conflict in Gemfile
Auto-merging CONTRIBUTING.md
CONFLICT (content): Merge conflict in CONTRIBUTING.md
Removing .travis.yml
Auto-merging .gitignore
Automatic merge failed; fix conflicts and then commit the result.
```
So those would be the conflicts to resolve. Rails 3 is not supported anymore and currently this is even roadblocking me to run the latest locally.  
The latest Redmine updated to Rails 4 which should solves all problems I'm having. Let me know what you guys think, depending on when this will happen it makes more sense for me to just wait before adding tokens, sessions detection etc otherwise I can look into this myself but it will take time from other things. Thanks!

**Comment by mattearnshaw** [comment]
I'm willing to try this merge tomorrow or Friday...

**Comment by mattearnshaw** [comment]
have also addressed your last two UI queries @ 2fbbc97

**Comment by tarelli** [comment]
@mattearnshaw hey Matt, how's the merge going?

**Comment by mattearnshaw** [comment]
@tarelli 10 more files to resolve, then we'll see if it works, will have an update this afternoon

**Comment by mattearnshaw** [comment]
@tarelli pushed what I have so far to `redmine333` branch. you need to run `rake db:migrate` for it to start. login is broken atm, and there are some styles that need to be fixed up but project pages are fine. will try and do these fixes tomorrow but you could at least see if you can get it running as-is.

**Comment by tarelli** [comment]
@mattearnshaw I can start it and project page works, sign up page has this error:
```
ActionView::Template::Error ((<unknown>): mapping values are not allowed in this context at line 1 column 137):
    70:     <!-- Introduce for recaptcha plugin-->
    71:     <div class="form-group">
    72:         <div class="col-sm-2 col-sm-offset-2">
    73:             <%= recaptcha_tags :site_key => Setting.plugin_recaptcha['recaptcha_public_key'] %>
    74:         </div>
    75:     </div>
    76: <% end %>
  app/models/setting.rb:97:in `value'
  app/models/setting.rb:110:in `[]'
  app/models/setting.rb:139:in `plugin_recaptcha'
  app/views/account/register.html.erb:73:in `block in _app_views_account_register_html_erb___3311546635914852792_70099669283980'
  app/helpers/application_helper.rb:1672:in `labelled_form_for'
  app/views/account/register.html.erb:3:in `_app_views_account_register_html_erb___3311546635914852792_70099669283980'
```

**Comment by mattearnshaw** [comment]
@tarelli hm, can't replicate this

**Comment by tarelli** [comment]
@mattearnshaw it disappears if I comment out 
```
    <!-- Introduce for recaptcha plugin-->
    <div class="form-group">
        <div class="col-sm-2 col-sm-offset-2">
            <%= recaptcha_tags :site_key => Setting.plugin_recaptcha['recaptcha_public_key'] %>
        </div>
    </div>
```

**Comment by tarelli** [comment]
@mattearnshaw let me know once the login works I'm starting to add security token etc.

**Comment by mattearnshaw** [comment]
@tarelli I pushed working login this morning

**Comment by tarelli** [comment]
@mattearnshaw In the signup page balloons not appearing anymore on hover over lightbulbs, also layout is a bit off

screen shot 2017-05-15 at 12 03 18

**Comment by tarelli** [comment]
@mattearnshaw layout glitch
screen shot 2017-05-24 at 11 42 50

**Pull request merged**
